name: environment
description: Air quality around the world

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/aqi_0.png
    - assets/images/aqi_51.png
    - assets/images/aqi_101.png
    - assets/images/aqi_151.png
    - assets/images/aqi_201.png
    - assets/images/aqi_301.png
